gpu: [0, 1]    #'0, 1, 2, 3'
work_mode: eval

dataset: WHU_RS19
image_size: 96
normalize_mean: [0.42599317, 0.44792527, 0.40231788]
normalize_std: [0.15217946, 0.1380795, 0.13700303]
train_dataset_path: ../../dataset/WHU_RS19/train
val_dataset_path: ../../dataset/WHU_RS19/val
test_dataset_path: ../../dataset/WHU_RS19/test
model_type: ResNet12
embed_size: 2560

way: 5
shot: 1
query: 15
seed: 999
test_episodes: 2000

dropout: 0.5
head: 10
temperature: 12

model_name: 50_0.5_0.0002_512mom_0.95_wd_0.0001_bsz_1



