gpu: [0, 1, 2, 3]
work_mode: train

dataset: WHU_RS19
image_size: 128
normalize_mean: [0.42599317, 0.44792527, 0.40231788]
normalize_std: [0.15217946, 0.1380795, 0.13700303]
train_dataset_path: ../../dataset/WHU_RS19/train
val_dataset_path: ../../dataset/WHU_RS19/val
test_dataset_path: ../../dataset/WHU_RS19/test
model_type: ResNet12
embed_size: 2560

way: 5
shot: 1

num_episodes_epoch: 80
num_eval_episodes:  600
query: 20

lr: 0.0002
lr_mul: 20
gamma: 0.5
max_epoch: 60
step_size: 50

seed: 999
dropout: 0.5
back_ward_step: 1
momentum: 0.95
weight_decay: 0.0001
nesterov: True

head: 10
final_weight: 1
ave_weight: 1
temperature: 512

checkpoint_dir: ./checkpoints
init_weights: True
init_weights_path: ./saves/initialization/mini-imagenet/IEPT_Res12_mini.pth
ngpu: 1

