gpu: [0, 1]    #'0, 1, 2, 3'
work_mode: eval

dataset: UCMerced_LandUse
image_size: 84
normalize_mean: [0.48422712, 0.4900519, 0.45050353]
normalize_std: [0.17342922, 0.16346784, 0.15541811]
train_dataset_path: ../../dataset/UCMerced_LandUse/train
val_dataset_path: ../../dataset/UCMerced_LandUse/val
test_dataset_path: ../../dataset/UCMerced_LandUse/test
model_type: ResNet12
embed_size: 640

way: 5
shot: 1
query: 15
seed: 999
test_episodes: 2000

dropout: 0.5
head: 10
temperature: 12

model_name: 50_0.5_0.0002_512mom_0.95_wd_0.0001_bsz_1



