gpu: [0, 1, 3]
work_mode: train

dataset: UCMerced_LandUse
image_size: 84
normalize_mean: [0.48422712, 0.4900519, 0.45050353]
normalize_std: [0.17342922, 0.16346784, 0.15541811]
train_dataset_path: ../../dataset/UCMerced_LandUse/train
val_dataset_path: ../../dataset/UCMerced_LandUse/val
test_dataset_path: ../../dataset/UCMerced_LandUse/test
model_type: ResNet12
embed_size: 640

way: 5
shot: 1

num_episodes_epoch: 80
num_eval_episodes:  600
query: 20

lr: 0.0002
lr_mul: 20
gamma: 0.5
max_epoch: 60
step_size: 50

dropout: 0.5
back_ward_step: 1
momentum: 0.95
weight_decay: 0.0001
nesterov: True

head: 10
final_weight: 1
ave_weight: 0.2
temperature: 512

checkpoint_dir: ./checkpoints
init_weights: True
init_weights_path: ./saves/initialization/mini-imagenet/IEPT_Res12_mini.pth
ngpu: 1

