gpu: [0, 1]
work_mode: train

dataset: NWPU_train_val_test
image_size: 128
normalize_mean: [0.36801773, 0.38097873, 0.34358302]
normalize_std: [0.14540215, 0.13558227, 0.13203649]
train_dataset_path: /media/D/jyy/dataset/NWPU_train_val_test/train
val_dataset_path: /media/D/jyy/dataset/NWPU_train_val_test/val
test_dataset_path: /media/D/jyy/dataset/NWPU_train_val_test/test
model_type: ConvNet
embed_size: 64

way: 5
shot: 1

num_episodes_epoch: 100
num_eval_episodes:  600
query: 20

lr: 0.0001
lr_mul: 10
gamma: 0.5
max_epoch: 200
step_size: 30

dropout: 0.5
back_ward_step: 1
momentum: 0.95
weight_decay: 0.0001
nesterov: True

head: 10
final_weight: 1
ave_weight: 0.5
temperature: 12

checkpoint_dir: ./checkpoints
init_weights: True
init_weights_path: ./saves/initialization/mini-imagenet/IEPT_Conv64_mini.pth
ngpu: 1

